pub mod json;
pub mod luau;
pub mod toml;
pub mod typescript;
pub mod typescript_declarations;

#[inline]
pub fn create_disclaimer_comment(comment_prefix: &'static str) -> String {
    format!(
        "{comment_prefix} This file is automatically @generated by Springroll {}.\
        \n{comment_prefix} It is not intended for manual editing.",
        env!("CARGO_PKG_VERSION")
    )
}

mod tests {
    #[test]
    pub fn disclaimer_comments() {
        assert_eq!(
            super::create_disclaimer_comment("--"),
            format!(
                "-- This file is automatically @generated by Springroll {}.\
                \n-- It is not intended for manual editing.",
                env!("CARGO_PKG_VERSION")
            )
        );

        assert_eq!(
            super::create_disclaimer_comment("//"),
            format!(
                "// This file is automatically @generated by Springroll {}.\
                \n// It is not intended for manual editing.",
                env!("CARGO_PKG_VERSION")
            )
        );
    }
}
