#[cfg(feature = "output_codegen_json")]
pub mod json;
#[cfg(feature = "output_codegen_luau")]
pub mod luau;
#[cfg(feature = "output_codegen_toml")]
pub mod toml;
#[cfg(feature = "output_codegen_ts")]
pub mod typescript;
#[cfg(feature = "output_codegen_dts")]
pub mod typescript_declarations;
#[cfg(feature = "output_codegen_yaml")]
pub mod yaml;

#[inline]
pub fn create_disclaimer_comment(comment_prefix: &'static str) -> String {
    format!(
        "{comment_prefix} This file is automatically @generated by Springroll {}.\
        \n{comment_prefix} It is not intended for manual editing.",
        env!("CARGO_PKG_VERSION")
    )
}

mod tests {
    #[test]
    pub fn disclaimer_comments() {
        assert_eq!(
            super::create_disclaimer_comment("--"),
            format!(
                "-- This file is automatically @generated by Springroll {}.\
                \n-- It is not intended for manual editing.",
                env!("CARGO_PKG_VERSION")
            )
        );

        assert_eq!(
            super::create_disclaimer_comment("//"),
            format!(
                "// This file is automatically @generated by Springroll {}.\
                \n// It is not intended for manual editing.",
                env!("CARGO_PKG_VERSION")
            )
        );
    }
}
